# Generated by Django 5.2.5 on 2025-08-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkoutLift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sets", models.PositiveSmallIntegerField()),
                ("reps", models.PositiveSmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
