# Generated by Django 5.2.5 on 2025-08-08 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlift",
            name="timeCreated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
