# Generated by Django 5.2.5 on 2025-08-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifts", "0002_workoutlift_timecreated"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiftData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sets", models.PositiveSmallIntegerField()),
                ("reps", models.PositiveSmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField()),
                ("timeCreated", models.DateTimeField(auto_now_add=True)),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifts.workoutlift",
                    ),
                ),
            ],
        ),
    ]
